### ISSUE TITLE
This task 'pacemaker' has extra  params, which is only allowed in the following modules:...

### ISSUE THREAD

**Issue by Dreamystify** [mrlesmithjr/ansible-pacemaker#1]
This task 'pacemaker' has extra  params, which is only allowed in the following modules:...

The code that triggers the error is:

```
- name: debian | configuring pacemaker cluster properties
  pacemaker: >
    property "{{ item.property }}"="{{ item.value }}"
  with_items: pacemaker_cluster_settings
  notify:
    - pacemaker commit
  when: pacemaker_cluster_settings is defined

- name: debian | disabling pacemaker STONITH
  pacemaker: >
    property stonith-enabled=false
  notify:
    - pacemaker commit
  when: pacemaker_disable_stonith is defined and pacemaker_disable_stonith
```

from the end of the debian.yml file

and if I uncomment the following lines in the handlers file:

```
# - name: pacemaker commit ###commented out for now...broken in ansible 2.0
#  pacemaker: commit
```

The same happens, Im using ansible 2.0.1.0. Any ideas whats going on? I'm new and ansible so I'm not much help debugging this kind of system

Cheers
